[package]
name = "http-rust-imagenet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
http = "0.2.9"
serde = { version = "1.0", features = ["derive"] }
spin-sdk = "2.2.0"
wit-bindgen = "0.26.0"
image2tensor = "0.3.1"
once_cell = "1.19.0"
tokio = { version = "1.38", features = ["sync"] }
mime = "^0.3.17"
multipart = "^0.18"
# Used by fileserver
flate2 = "1.0.28"
futures = "0.3.28"
sha2 = "0.10.8"
brotli = "3.3" # Brotli compression makes big things less big
mime_guess = "2.0"
hex = "0.4.3"

rust_tokenizers = "8.1.0"

[workspace]
