[package]
name = "spin-ml"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
tokio = "1.0"

spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
table = { path = "../table" }

openvino = { version = "0.7.2", features = ["runtime-linking",], optional = true }

curl = { version = "^0.4", features = ["rustls"] }
sha1 = "^0.10"
hex-literal = "^0.4"
hex =  "^0.4"

tracing = { workspace = true }

llm = { git = "https://github.com/rustformers/llm", rev = "2f6ffd4435799ceaa1d1bcb5a8790e5b3e0c5663", features = [
    "tokenizers-remote",
    "llama",
], default-features = false }

[features]
default = ["openvino"]
openvino = ["dep:openvino"]
has_gpu = []
